name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Debug secrets
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "SSH_HOST=${SSH_HOST}"
        echo "SSH_USER=${SSH_USER}"
        # Do not echo sensitive secrets in production workflows
        # echo "SSH_PASSWORD=${SSH_PASSWORD}"


    - name: Deploy
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -vvv -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'cd /var/www/admin-tailwind && git pull && npm install && npm run build'
